name: Base 
description: Parallelcluster base software and dependencies
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: base-extras
        action: ExecuteBash
        inputs:
          commands:
            # Install basics
            - |
              yum update -y
              yum install -y \
                amazon-linux-extras \
                tmux
                htop
                wget
            # Install packages inside amazon-linux-extras
            - |
              amazon-linux-extras install -y \
                epel \
                vim \
                docker \
                lustre2.10 \
                livepatch \
                R3.4 \
                python3.8 \
                ruby2.4 \
                golang1.11 \
                rust1 \
                java-openjdk11
            # Create alias for python3
            - |
              ln -s /usr/bin/python3.8 /usr/bin/python3
            # Install awstoe
            # Handy, for (in-cluster) AMI building: https://docs.aws.amazon.com/imagebuilder/latest/userguide/image-builder-component-manager-local.html
            - |
              wget https://awstoe-ap-southeast-2.s3.ap-southeast-2.amazonaws.com/latest/linux/amd64/awstoe \
                -O /usr/local/bin/awstoe
              chmod +x /usr/local/bin/awstoe
            # Install parallel-cluster commands via pip into ec2-user account
            - |
              su - ec2-user
                -c "curl -O https://bootstrap.pypa.io/get-pip.py && \
                    python3 get-pip.py --user && \
                    pip3 install --upgrade pip && \
                    pip3 install aws-parallelcluster --user"
            # Set mountpoints and assign ownership to ec2-user
            - |
              mkdir -p /scratch && chown ec2-user:ec2-user /scratch
              mkdir -p /mnt/refdata && chown ec2-user:ec2-user /mnt/refdata
              mkdir -p /mnt/data && chown ec2-user:ec2-user /mnt/data