name: Base 
description: Parallelcluster base software and dependencies
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: base-extras
        action: ExecuteBash
        inputs:
          commands:
            - yum install -y amazon-linux-extras
            - yum install -y tmux htop
            - amazon-linux-extras install -y epel vim docker lustre2.10 livepatch
            - amazon-linux-extras install -y R3.4 python3.8 ruby2.4 golang1.11 rust1 java-openjdk11
            # Handy, for (in-cluster) AMI building: https://docs.aws.amazon.com/imagebuilder/latest/userguide/image-builder-component-manager-local.html
            - wget https://awstoe-ap-southeast-2.s3.ap-southeast-2.amazonaws.com/latest/linux/amd64/awstoe -O /usr/local/bin/awstoe
            - chmod +x /usr/local/bin/awstoe
            #- pip3 install aws-parallelcluster --upgrade --user XXX: generates dkpg-dev install-time issues?:
            # See: https://github.com/aws/aws-parallelcluster/issues/1903#issuecomment-665426575
            - mkdir -p /scratch && chown ec2-user:ec2-user /scratch
            - mkdir -p /mnt/refdata && chown ec2-user:ec2-user /mnt/refdata
            - mkdir -p /mnt/data && chown ec2-user:ec2-user /mnt/data