name: Conda 
description: Miniconda ready for Bioinformatics
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: anaconda
        action: ExecuteBash
        inputs:
          commands:
            # https://github.com/dcbark01/AnacondaInstallEC2/blob/master/install.sh
            - su - ec2-user -c "wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && chmod +x miniconda.sh"
            - su - ec2-user -c "./miniconda.sh -b -p /home/ec2-user/.conda"
            - su - ec2-user -c "rm miniconda.sh"
            - su - ec2-user -c "echo '. /home/ec2-user/.conda/etc/profile.d/conda.sh' >> /home/ec2-user/.bashrc"
            - su - ec2-user -c "echo 'channels:' >> /home/ec2-user/.condarc"
            - su - ec2-user -c "echo '  - conda-forge' >> /home/ec2-user/.condarc"
            - su - ec2-user -c "echo '  - bioconda' >> /home/ec2-user/.condarc"
            - su - ec2-user -c "echo '  - defaults' >> /home/ec2-user/.condarc"
            - su - ec2-user -c "source /home/ec2-user/.bashrc && conda update -n base conda -y"
