resources:
  machine:
    memory: 62
    cores: 16
  default:
    cores: 4
    jvm_opts:
      - -Xms2000m
      - -Xmx12000m
    memory: 14G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  macs2:
    memory: 8g
  qualimap:
    memory: 4g
  seqcluster:
    memory: 8g
  snpeff:
    jvm_opts:
      - -Xms750m
      - -Xmx3g